apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  POSTGRES_DB: ZGVtb2RiCg==   #mta_data
  POSTGRES_USER: cG9zdGdyZXM=   #postgres 
  POSTGRES_PASSWORD: YWRtaW4xMjMK     #admin123
