apiVersion: v1
kind: Service
metadata:
  name: sbdemo-nginx-service
spec:
  type: ClusterIP
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 80
     targetPort: 80
  selector:
    app: sbdemo-nginx
