apiVersion: v1
kind: ConfigMap
metadata:
  name: server-conf
data: 
  server {
      server_name  springdemo.example.com;
      listen 80;

      location ~* \.(js|jpg|png|css)$ {
          expires 168h;
          root   /usr/share/nginx/html;
      }

      location / {
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;
          proxy_pass http://sbdemo-apserver-service:8080;
          proxy_cookie_path / /;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
  }

