apiVersion: v1
kind: Service
metadata:
  name: sbdemo-apserver-service
spec:
  type: ClusterIP
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 8080
     targetPort: 8080
  selector:
    app: sbdemo-apserver
