apiVersion: v1
kind: PersistentVolume
metadata:
  name: sbdemo-nfs-pv
  labels:
    role: nfs-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    # server ip must be changed
    server: 172.31.12.178 
    path: "/"
